import React from 'react';
import { checkPublicReservasWebContact, createPublicReservasWebHold, createPublicReservasWebReservation, type PublicReservasWebActivity, type PublicReservasWebHold, type PublicReservasWebReservation } from '../../../services/reservasWebPublicApi';
import { createReservasWebBookingDraft, ReservasWebBookingForm, resolveReservasWebResponsible, type ReservasWebBookingDraft, validateReservasWebBookingDraft } from './ReservasWebBookingForm';

type State = 'idle' | 'choosing_quantity' | 'creating_hold' | 'form' | 'checking_contact' | 'review' | 'submitting' | 'success' | 'hold_expired' | 'error';
type Props = { moduleId: string; publicIdentifier: string; activity: PublicReservasWebActivity; label: string; ctaBackgroundColor: string; ctaTextColor: string; onRefreshActivity: () => void };
const key = () => crypto.randomUUID();
export const getHoldCountdownLabel = (expiresAt: string, now = Date.now()) => { const ms = Date.parse(expiresAt) - now; if (!Number.isFinite(ms) || ms <= 0) return null; const seconds = Math.ceil(ms / 1000); return `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; };
export const isReservasWebHoldExpired = (expiresAt: string, now = Date.now()) => getHoldCountdownLabel(expiresAt, now) === null;
const money = (value: number, currency: string) => new Intl.NumberFormat('es', { style: 'currency', currency }).format(value);
const clearSensitive = (draft: ReservasWebBookingDraft): ReservasWebBookingDraft => ({ ...draft, participants: draft.participants.map(({ identificationNumber: _id, ...person }) => ({ ...person, identificationNumber: '' })) });
const paymentFor = (activity: PublicReservasWebActivity, quantity: number, mode: 'full' | 'deposit') => { const total = activity.pricing.effectivePrice * quantity; const requiredAmount = mode === 'deposit' ? Number(activity.pricing.depositAmountPerPerson || 0) * quantity : total; return { total, requiredAmount, pendingBalance: Math.max(0, total - requiredAmount) }; };
export const normalizeReservasWebBookingQuantity = (value: string, maximum: number) => Math.min(maximum, Math.max(1, Number.parseInt(value, 10) || 1));

const Review = ({ activity, draft, quantity, paymentMethod, paymentMode, warning, onPaymentMethod, onPaymentMode, onEdit, onSubmit, disabled }: { activity: PublicReservasWebActivity; draft: ReservasWebBookingDraft; quantity: number; paymentMethod: 'sinpe' | 'card' | null; paymentMode: 'full' | 'deposit' | null; warning: boolean; onPaymentMethod: (value: 'sinpe' | 'card') => void; onPaymentMode: (value: 'full' | 'deposit') => void; onEdit: () => void; onSubmit: () => void; disabled: boolean }) => {
  const paid = !activity.pricing.isFree; const methods = activity.paymentMethods; const options = activity.pricing.paymentOptions; const mode = paymentMode || options[0] || 'full'; const calculation = paymentFor(activity, quantity, mode); const responsible = resolveReservasWebResponsible(draft);
  return <section className="space-y-3 rounded-lg border border-border/60 p-3"><h3 className="font-semibold">Revisa tus datos</h3><p className="text-sm">{activity.title} · {quantity} participante{quantity === 1 ? '' : 's'}</p><ul className="space-y-1 text-sm">{draft.participants.map((participant, index) => <li key={index}>Participante {index + 1}: {participant.firstName.trim()} {participant.lastName.trim()}</li>)}</ul><p className="text-sm">Responsable: {responsible.firstName.trim()} {responsible.lastName.trim()}</p><p className="text-sm">WhatsApp: {responsible.whatsapp.trim()}</p>{warning && <p role="status" className="rounded-lg bg-secondary p-3 text-sm">Ya existen reservas asociadas a este WhatsApp.</p>}{paid && options.length > 1 && <fieldset className="space-y-2"><legend className="font-semibold">¿Cómo deseas pagar?</legend><label className="block"><input type="radio" checked={mode === 'full'} onChange={() => onPaymentMode('full')} /> Pagar el total — {money(paymentFor(activity, quantity, 'full').requiredAmount, activity.pricing.currency)}</label><label className="block"><input type="radio" checked={mode === 'deposit'} onChange={() => onPaymentMode('deposit')} /> Reservar con pago parcial — {money(paymentFor(activity, quantity, 'deposit').requiredAmount, activity.pricing.currency)}</label></fieldset>}{paid && methods.length > 1 && <label className="block text-sm font-semibold">Método de pago<select value={paymentMethod || ''} disabled={disabled} onChange={(event) => onPaymentMethod(event.target.value as 'sinpe' | 'card')} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 font-normal"><option value="">Selecciona un método</option>{methods.map((method) => <option key={method} value={method}>{method === 'sinpe' ? 'SINPE' : 'Tarjeta'}</option>)}</select></label>}<p className="text-sm">Total: {money(calculation.total, activity.pricing.currency)}</p>{paid && <><p className="text-sm">Pago requerido ahora: {money(calculation.requiredAmount, activity.pricing.currency)}</p>{mode === 'deposit' && <><p className="text-sm">Saldo pendiente: {money(calculation.pendingBalance, activity.pricing.currency)}</p><p className="text-sm">El monto de reserva es {activity.pricing.depositRefundable ? 'reembolsable' : 'no reembolsable'}.</p></>}</>}<div className="flex gap-2"><button type="button" disabled={disabled} onClick={onEdit} className="rounded-lg border border-border px-3 py-2 text-sm">Editar datos</button><button type="button" disabled={disabled || (paid && (!paymentMethod || !methods.includes(paymentMethod) || !options.includes(mode)))} onClick={onSubmit} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-white disabled:text-white disabled:opacity-50">{disabled ? <span className="inline-flex items-center gap-2"><span aria-hidden="true" className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent" />Procesando reserva</span> : 'Confirmar reserva'}</button></div></section>;
};
const formatPaymentDueAt = (value: string, timeZone: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toLocaleString('es', { dateStyle: 'medium', timeStyle: 'short', timeZone }); };
export const ReservasWebBookingResult = ({ activity, reservation }: { activity: PublicReservasWebActivity; reservation: PublicReservasWebReservation }) => {
  const hasPerPersonPaymentAmount = typeof reservation.perPersonPaymentAmount === 'number';
  const perPerson = hasPerPersonPaymentAmount ? money(reservation.perPersonPaymentAmount, reservation.currency) : null;
  const paymentLabel = perPerson ? (reservation.paymentMode === 'deposit' ? `Pagar reserva · ${perPerson} por persona` : `Pagar total · ${perPerson} por persona`) : null;
  const dueAt = reservation.paymentDueAt ? formatPaymentDueAt(reservation.paymentDueAt, activity.timezone) : null; const isPendingPayment = reservation.status === 'pending_payment';
  return <section className="space-y-3 rounded-lg border border-border/60 p-3"><h3 className="font-semibold">{reservation.status === 'confirmed' ? 'Reserva confirmada' : 'Espacios reservados — pago pendiente'}</h3><p>{activity.title} · {reservation.quantity} participante{reservation.quantity === 1 ? '' : 's'}</p><p>Referencia: {reservation.reservationReference}</p>{isPendingPayment && <><div className="space-y-1 rounded-lg bg-secondary p-3 text-sm"><p>Total: {money(reservation.totalAmount, reservation.currency)}</p><p>Pago requerido ahora: {money(reservation.requiredNow, reservation.currency)}</p><p>Saldo pendiente: {money(reservation.pendingBalance, reservation.currency)}</p>{reservation.paymentMode === 'deposit' && <p>El monto de reserva es {reservation.depositRefundable ? 'reembolsable' : 'no reembolsable'}.</p>}</div>{reservation.quantity > 1 && perPerson && <p className="rounded-lg border border-border/60 p-3 text-sm">Registraste {reservation.quantity} personas. El enlace de pago corresponde a {perPerson} por persona, por lo que debes realizar el pago {reservation.quantity} veces.</p>}{!perPerson && <p role="status" className="rounded-lg bg-secondary p-3 text-sm">No fue posible determinar el monto por persona para el enlace de pago.</p>}{reservation.paymentUrl && paymentLabel && <a href={reservation.paymentUrl} target="_blank" rel="noopener noreferrer" className="block w-full break-words rounded-lg bg-primary px-4 py-3 text-center font-semibold text-white">{paymentLabel}</a>}<p className="rounded-lg bg-secondary p-3 text-sm">La reserva se mantendrá por un máximo de 24 horas mientras se confirma el pago. Si el pago no es confirmado dentro de ese plazo, la reserva queda sujeta a cancelación.{dueAt ? ` Vence el ${dueAt}.` : ''}</p>{reservation.paymentReceiptWhatsapp && <p className="rounded-lg border border-border/60 p-3 text-sm">Después de realizar el pago, envía la imagen del comprobante al WhatsApp {reservation.paymentReceiptWhatsapp}.</p>}</>}{reservation.payment.method === 'sinpe' && <div className="text-sm">{reservation.payment.phone && <p>SINPE: {reservation.payment.phone}</p>}{reservation.payment.beneficiary && <p>Beneficiario: {reservation.payment.beneficiary}</p>}</div>}</section>;
};

type QuantityControlProps = { value: string; disabled: boolean; onChange: (value: string) => void; onNormalize: () => void; onDecrement: () => void; onIncrement: () => void };
export const ReservasWebBookingQuantityControl = ({ value, disabled, onChange, onNormalize, onDecrement, onIncrement }: QuantityControlProps) => <label className="block text-sm font-semibold">¿Cuántas personas desea reservar?<div className="mt-1 flex min-w-0 items-center gap-2"><button type="button" aria-label="Disminuir cantidad" disabled={disabled} onClick={onDecrement} className="min-h-[44px] min-w-[44px] shrink-0 rounded-lg border border-border px-3 py-2 disabled:opacity-50">−</button><input type="text" inputMode="numeric" value={value} disabled={disabled} onChange={event => { if (/^\d*$/.test(event.target.value)) onChange(event.target.value); }} onBlur={onNormalize} className="min-w-0 flex-1 rounded-lg border border-border bg-background px-3 py-2 text-center" /><button type="button" aria-label="Aumentar cantidad" disabled={disabled} onClick={onIncrement} className="min-h-[44px] min-w-[44px] shrink-0 rounded-lg border border-border px-3 py-2 disabled:opacity-50">+</button></div></label>;

export const ReservasWebBookingStart = ({ moduleId, publicIdentifier, activity, label, ctaBackgroundColor, onRefreshActivity }: Props) => {
  const maximum = Math.max(1, Math.min(100, typeof activity.capacity.available === 'number' ? activity.capacity.available : 100)); const [state, setState] = React.useState<State>('idle'); const [quantity, setQuantity] = React.useState(1); const [quantityInput, setQuantityInput] = React.useState('1'); const [hold, setHold] = React.useState<PublicReservasWebHold | null>(null); const [draft, setDraft] = React.useState(() => createReservasWebBookingDraft(1)); const [paymentMethod, setPaymentMethod] = React.useState<'sinpe' | 'card' | null>(null); const [paymentMode, setPaymentMode] = React.useState<'full' | 'deposit' | null>(null); const [warning, setWarning] = React.useState(false); const [result, setResult] = React.useState<PublicReservasWebReservation | null>(null); const [now, setNow] = React.useState(Date.now()); const submittingRef = React.useRef(false);
  React.useEffect(() => { if (state !== 'form' && state !== 'review') return; const interval = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(interval); }, [state]);
  React.useEffect(() => { if (hold && (state === 'form' || state === 'review') && isReservasWebHoldExpired(hold.expiresAt, now)) setState('hold_expired'); }, [hold, now, state]);
  const normalizeQuantity = () => { const next = normalizeReservasWebBookingQuantity(quantityInput, maximum); setQuantity(next); setQuantityInput(String(next)); return next; };
  const startHold = async () => { const nextQuantity = normalizeQuantity(); setState('creating_hold'); try { const next = await createPublicReservasWebHold(publicIdentifier, nextQuantity, key()); setDraft(current => createReservasWebBookingDraft(next.quantity, current)); setHold(next); setState('form'); onRefreshActivity(); } catch { setState('error'); } };
  const review = async () => { if (!hold || isReservasWebHoldExpired(hold.expiresAt) || Object.keys(validateReservasWebBookingDraft(draft, hold.quantity)).length) { if (hold && isReservasWebHoldExpired(hold.expiresAt)) setState('hold_expired'); return; } const responsible = resolveReservasWebResponsible(draft); setState('checking_contact'); setWarning(await checkPublicReservasWebContact(publicIdentifier, responsible.whatsapp).catch(() => false)); setPaymentMethod(activity.pricing.isFree ? null : activity.paymentMethods.length === 1 ? activity.paymentMethods[0] : null); setPaymentMode(activity.pricing.isFree ? null : activity.pricing.paymentOptions.length === 1 ? activity.pricing.paymentOptions[0] : null); setState('review'); };
  const submit = async () => { if (submittingRef.current || !hold || isReservasWebHoldExpired(hold.expiresAt) || Object.keys(validateReservasWebBookingDraft(draft, hold.quantity)).length) { if (hold && isReservasWebHoldExpired(hold.expiresAt)) setState('hold_expired'); return; } const mode = activity.pricing.isFree ? null : paymentMode; if (!activity.pricing.isFree && (!paymentMethod || !mode || !activity.pricing.paymentOptions.includes(mode))) return; submittingRef.current = true; const responsible = resolveReservasWebResponsible(draft); setState('submitting'); try { const response = await createPublicReservasWebReservation({ holdToken: hold.holdToken, idempotencyKey: key(), contactFirstName: responsible.firstName.trim(), contactLastName: responsible.lastName.trim(), contactWhatsapp: responsible.whatsapp.trim(), paymentMethod, paymentMode: mode, participants: draft.participants.map(participant => ({ ...participant, age: Number(participant.age), sex: participant.sex as 'male' | 'female' | 'prefer_not_to_say' })) }); setResult(response.reservation); setDraft(clearSensitive(draft)); setHold(null); setState('success'); onRefreshActivity(); } catch { submittingRef.current = false; setState('review'); } };
  if (state === 'success' && result) return <ReservasWebBookingResult activity={activity} reservation={result} />;
  if (state === 'hold_expired') return <section role="status" className="space-y-3 rounded-lg border border-border/60 p-3"><p>El tiempo para completar el registro venció. Por favor, inténtalo de nuevo.</p><button type="button" onClick={() => { setHold(null); setState('idle'); }} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-white">Volver al inicio</button></section>;
  if (state === 'form' && hold) return <ReservasWebBookingForm moduleId={moduleId} quantity={hold.quantity} countdown={getHoldCountdownLabel(hold.expiresAt, now) || '00:00'} disabled={isReservasWebHoldExpired(hold.expiresAt, now)} draft={draft} onDraftChange={setDraft} onChangeQuantity={() => { setHold(null); setState('choosing_quantity'); }} onReview={() => void review()} />;
  if ((state === 'review' || state === 'submitting') && hold) return <Review activity={activity} draft={draft} quantity={hold.quantity} paymentMethod={paymentMethod} paymentMode={paymentMode} warning={warning} onPaymentMethod={setPaymentMethod} onPaymentMode={setPaymentMode} onEdit={() => setState('form')} onSubmit={() => void submit()} disabled={state === 'submitting' || isReservasWebHoldExpired(hold.expiresAt, now)} />;
  if (state === 'choosing_quantity' || state === 'creating_hold' || state === 'error') return <div className="space-y-3 rounded-lg border border-border/60 p-3"><ReservasWebBookingQuantityControl value={quantityInput} disabled={state === 'creating_hold'} onChange={setQuantityInput} onNormalize={normalizeQuantity} onDecrement={() => { const next = Math.max(1, normalizeReservasWebBookingQuantity(quantityInput, maximum) - 1); setQuantity(next); setQuantityInput(String(next)); }} onIncrement={() => { const next = Math.min(maximum, normalizeReservasWebBookingQuantity(quantityInput, maximum) + 1); setQuantity(next); setQuantityInput(String(next)); }} /><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setState('idle')} className="rounded-lg border border-border px-3 py-2 text-sm">Cancelar</button><button type="button" disabled={state === 'creating_hold'} onClick={() => void startHold()} style={{ backgroundColor: ctaBackgroundColor || undefined }} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-white disabled:text-white disabled:opacity-50">{state === 'creating_hold' ? 'Reservando…' : 'Continuar'}</button></div></div>;
  return <button type="button" disabled={!activity.booking.enabled} onClick={() => { setQuantity(1); setQuantityInput('1'); setState('choosing_quantity'); }} style={{ backgroundColor: ctaBackgroundColor || undefined }} className="w-full rounded-lg bg-primary px-4 py-3 font-semibold text-white disabled:text-white disabled:opacity-50">{label}</button>;
};
