import React from 'react';

export type ReservasWebContactDraft = { contactFirstName: string; contactLastName: string; contactWhatsapp: string };
export type ReservasWebParticipantDraft = { firstName: string; lastName: string; sex: '' | 'male' | 'female' | 'prefer_not_to_say'; birthDate: string; identificationNumber: string };
export type ReservasWebBookingDraft = ReservasWebContactDraft & { participants: ReservasWebParticipantDraft[] };
export type ReservasWebBookingErrors = Record<string, string>;
const blankParticipant = (): ReservasWebParticipantDraft => ({ firstName: '', lastName: '', sex: '', birthDate: '', identificationNumber: '' });
export const createReservasWebBookingDraft = (quantity: number, existing?: ReservasWebBookingDraft): ReservasWebBookingDraft => ({ contactFirstName: existing?.contactFirstName || '', contactLastName: existing?.contactLastName || '', contactWhatsapp: existing?.contactWhatsapp || '', participants: Array.from({ length: quantity }, (_, index) => existing?.participants[index] || blankParticipant()) });
const text = (value: string) => value.trim();
const isBirthDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && new Date(`${value}T00:00:00.000Z`).toISOString().slice(0, 10) === value;
const isWhatsapp = (value: string) => { const digits = text(value).replace(/\D/g, ''); return digits.length >= 7 && digits.length <= 20; };
export const validateReservasWebBookingDraft = (draft: ReservasWebBookingDraft, quantity: number, today = new Date().toISOString().slice(0, 10)): ReservasWebBookingErrors => {
  const errors: ReservasWebBookingErrors = {};
  if (!text(draft.contactFirstName) || text(draft.contactFirstName).length > 100) errors.contactFirstName = 'Ingresa un nombre válido.';
  if (!text(draft.contactLastName) || text(draft.contactLastName).length > 100) errors.contactLastName = 'Ingresa un apellido válido.';
  if (!isWhatsapp(draft.contactWhatsapp)) errors.contactWhatsapp = 'Ingresa un WhatsApp válido.';
  if (draft.participants.length !== quantity) errors.participants = 'La cantidad de participantes debe coincidir con los espacios reservados.';
  draft.participants.forEach((participant, index) => { const prefix = `participants.${index}`; if (!text(participant.firstName) || text(participant.firstName).length > 100) errors[`${prefix}.firstName`] = 'Ingresa un nombre válido.'; if (!text(participant.lastName) || text(participant.lastName).length > 100) errors[`${prefix}.lastName`] = 'Ingresa un apellido válido.'; if (!['male', 'female', 'prefer_not_to_say'].includes(participant.sex)) errors[`${prefix}.sex`] = 'Selecciona una opción.'; if (!isBirthDate(participant.birthDate) || participant.birthDate > today) errors[`${prefix}.birthDate`] = 'Ingresa una fecha de nacimiento válida.'; if (!text(participant.identificationNumber) || text(participant.identificationNumber).length > 64) errors[`${prefix}.identificationNumber`] = 'Ingresa una identificación válida.'; });
  return errors;
};
type Props = { moduleId: string; activityTitle?: string; quantity: number; countdown: string; draft: ReservasWebBookingDraft; disabled?: boolean; onDraftChange: (draft: ReservasWebBookingDraft) => void; onChangeQuantity: () => void; onReview?: () => void };
const FieldError = ({ error }: { error?: string }) => error ? <p className="text-xs text-red-700">{error}</p> : null;
export const ReservasWebBookingForm = ({ moduleId, quantity, countdown, draft, disabled = false, onDraftChange, onChangeQuantity, onReview = () => {} }: Props) => {
  const [errors, setErrors] = React.useState<ReservasWebBookingErrors>({});
  const updateContact = (key: keyof ReservasWebContactDraft, value: string) => onDraftChange({ ...draft, [key]: value });
  const updateParticipant = (index: number, key: keyof ReservasWebParticipantDraft, value: string) => onDraftChange({ ...draft, participants: draft.participants.map((participant, participantIndex) => participantIndex === index ? { ...participant, [key]: value } : participant) });
  const continueToReview = () => { const next = validateReservasWebBookingDraft(draft, quantity); setErrors(next); if (!Object.keys(next).length) onReview(); };
  return <section className="space-y-4 rounded-lg border border-border/60 p-3"><p aria-live="polite" className="rounded-lg bg-secondary p-3 text-sm">Tus espacios están reservados por {countdown}.</p><div className="space-y-3"><h3 className="font-semibold">Responsable de la reserva</h3>{([['contactFirstName', 'Nombre'], ['contactLastName', 'Apellido'], ['contactWhatsapp', 'WhatsApp']] as const).map(([key, label]) => <label key={key} className="block text-sm font-semibold">{label}<input id={`${moduleId}-${key}`} disabled={disabled} value={draft[key]} onChange={(event) => updateContact(key, event.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 font-normal" /><FieldError error={errors[key]} /></label>)}</div><div className="space-y-3">{draft.participants.map((participant, index) => <fieldset key={index} disabled={disabled} className="space-y-3 rounded-lg border border-border/60 p-3"><legend className="px-1 text-sm font-semibold">Participante {index + 1}</legend>{([['firstName', 'Nombre', 'text'], ['lastName', 'Apellido', 'text'], ['birthDate', 'Fecha de nacimiento', 'date'], ['identificationNumber', 'Identificación', 'text']] as const).map(([key, label, type]) => <label key={key} className="block text-sm font-semibold">{label}<input type={type} value={participant[key]} onChange={(event) => updateParticipant(index, key, event.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 font-normal" /><FieldError error={errors[`participants.${index}.${key}`]} /></label>)}<label className="block text-sm font-semibold">Sexo<select value={participant.sex} onChange={(event) => updateParticipant(index, 'sex', event.target.value)} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 font-normal"><option value="">Selecciona una opción</option><option value="male">Masculino</option><option value="female">Femenino</option><option value="prefer_not_to_say">Prefiero no indicarlo</option></select><FieldError error={errors[`participants.${index}.sex`]} /></label></fieldset>)}</div>{errors.participants && <p role="status" className="text-sm text-red-700">{errors.participants}</p>}<div className="flex gap-2"><button type="button" disabled={disabled} onClick={onChangeQuantity} className="rounded-lg border border-border px-3 py-2 text-sm">Cambiar cantidad</button><button type="button" disabled={disabled} onClick={continueToReview} className="rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">{disabled ? 'Verificando…' : 'Continuar'}</button></div></section>;
};
