import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, MapPin, Upload, X, Check, EyeOff, RefreshCw } from 'lucide-react';
import { specialEventApi, SpecialEventApiError, type SpecialEventPhoto } from '../../../services/specialEventApi';
import { resolveSpecialEventModerationToken } from '../../../utils/specialEventModerationPath';

const value = (settings: Record<string, any>, id: string, fallback: any) => settings[id] ?? fallback;
const key = (moduleId: string, group: string, id: string) => `${moduleId}_${group}_${id}`;
const readableError = (error: unknown) => { const code = error instanceof SpecialEventApiError ? error.code : ''; if (code === 'SPECIAL_EVENT_UPLOAD_RATE_LIMITED') return 'Hemos recibido muchas cargas. Intenta de nuevo en unos minutos.'; if (code === 'SPECIAL_EVENT_NOT_FOUND') return 'Este evento aún no está disponible.'; if (code.startsWith('IMAGE_')) return 'Una de las fotografías no cumple los requisitos.'; return 'No pudimos completar la operación. Intenta nuevamente.'; };

export const SpecialEventModule: React.FC<{ moduleId: string; settingsValues: Record<string, any> }> = ({ moduleId, settingsValues }) => {
  const renderPublicEventDetails = false;
  const slug = String(value(settingsValues, key(moduleId, 'el_special_event_identity', 'slug'), '')).trim();
  const title = value(settingsValues, key(moduleId, 'el_special_event_cover', 'title'), 'Evento especial');
  const subtitle = value(settingsValues, key(moduleId, 'el_special_event_cover', 'subtitle'), '');
  const story = value(settingsValues, key(moduleId, 'el_special_event_carousel', 'images'), []) as Array<{ url: string; alt?: string }>;
  const [slide, setSlide] = useState(0); const [photos, setPhotos] = useState<SpecialEventPhoto[]>([]); const [filter, setFilter] = useState('all'); const [selected, setSelected] = useState<number | null>(null);
  const [files, setFiles] = useState<File[]>([]); const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [uploading, setUploading] = useState(false); const [progress, setProgress] = useState(0); const [notice, setNotice] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  const primary = value(settingsValues, key(moduleId, 'el_special_event_cover', 'primary_color'), '#D99AAA'); const bg = value(settingsValues, key(moduleId, 'el_special_event_cover', 'background_color'), '#FFF9F5'); const text = value(settingsValues, key(moduleId, 'el_special_event_cover', 'text_color'), '#4B3440');
  const moderationToken = typeof window !== 'undefined'
    ? resolveSpecialEventModerationToken(window.location.pathname, window.location.search)
    : '';
  const [moderationStatus, setModerationStatus] = useState<'pending' | 'approved'>('pending'); const [moderationPhotos, setModerationPhotos] = useState<SpecialEventPhoto[]>([]); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [moderationError, setModerationError] = useState(''); const [moderating, setModerating] = useState(false);
  const loadGallery = async (signal?: AbortSignal) => { if (!slug) return; try { setPhotos(await specialEventApi.getPhotos(slug, signal)); } catch { /* public state remains usable while backend is activated */ } };
  useEffect(() => { const controller = new AbortController(); void loadGallery(controller.signal); const timer = window.setInterval(() => { if (document.visibilityState === 'visible') void loadGallery(); }, 30000); return () => { controller.abort(); window.clearInterval(timer); }; }, [slug]);
  useEffect(() => { if (!story.length || !value(settingsValues, key(moduleId, 'el_special_event_carousel', 'autoplay'), true)) return; const timer = window.setInterval(() => setSlide((current) => (current + 1) % story.length), 5000); return () => window.clearInterval(timer); }, [story.length, settingsValues, moduleId]);
  const contributors = useMemo(() => Array.from(new Map(photos.map((photo) => [photo.contributor.id, photo.contributor])).values()), [photos]);
  const filtered = filter === 'all' ? photos : photos.filter((photo) => photo.contributor.id === filter);
  const pickFiles = (list: FileList | null) => { const next = Array.from(list || []); if (next.length + files.length > 10) return setNotice('Puedes seleccionar un máximo de 10 fotografías.'); if (next.some((file) => !['image/jpeg', 'image/png'].includes(file.type) || file.size > 15 * 1024 * 1024)) return setNotice('Usa únicamente JPEG o PNG de hasta 15 MB.'); setNotice(''); setFiles((current) => [...current, ...next]); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim() || !files.length) return setNotice('Indica tu nombre y selecciona al menos una fotografía.'); setUploading(true); setProgress(0); try { const result = await specialEventApi.uploadPhotos(slug, { name: name.trim(), message: message.trim(), files, onProgress: setProgress }); setFiles([]); setName(''); setMessage(''); setNotice(result.failures?.length ? 'Algunas fotos no pudieron cargarse; las demás fueron recibidas para aprobación.' : '¡Gracias por compartir estos recuerdos! Tus fotografías aparecerán cuando sean aprobadas.'); } catch (error) { setNotice(readableError(error)); } finally { setUploading(false); } };
  const loadModeration = async () => { if (!slug || !moderationToken) return; setModerationError(''); try { setModerationPhotos(await specialEventApi.moderationPhotos(slug, moderationToken, moderationStatus)); } catch (error) { setModerationError(readableError(error)); } };
  useEffect(() => { if (moderationToken) void loadModeration(); }, [moderationToken, slug, moderationStatus]);
  const moderate = async (ids: string[], status: 'approved' | 'hidden') => { if (!ids.length) return; setModerating(true); try { await specialEventApi.moderate(slug, moderationToken, ids, status); setModerationPhotos((current) => current.filter((photo) => !ids.includes(photo.id))); setSelectedIds([]); } catch (error) { setModerationError(readableError(error)); } finally { setModerating(false); } };
  if (moderationToken) return <section className="min-h-screen p-4 sm:p-8" style={{ background: bg, color: text }}><div className="mx-auto max-w-3xl"><h1 className="text-3xl font-black">{title}</h1><p className="mb-6">Moderación de fotografías</p><div className="mb-4 flex gap-2"><button onClick={() => setModerationStatus('pending')} className="rounded-full px-4 py-2" style={{ background: moderationStatus === 'pending' ? primary : '#fff' }}>Pendientes</button><button onClick={() => setModerationStatus('approved')} className="rounded-full bg-white px-4 py-2">Publicadas</button><button onClick={() => void loadModeration()} className="ml-auto rounded-full bg-white p-2" aria-label="Actualizar"><RefreshCw size={18}/></button></div>{selectedIds.length > 0 && <div className="mb-4 flex gap-2"><button disabled={moderating} onClick={() => void moderate(selectedIds, 'approved')} className="rounded-xl bg-emerald-600 px-4 py-3 font-bold text-white">Aprobar ({selectedIds.length})</button><button disabled={moderating} onClick={() => void moderate(selectedIds, 'hidden')} className="rounded-xl bg-slate-700 px-4 py-3 font-bold text-white">Ocultar</button></div>}{moderationError && <p className="mb-4 rounded-xl bg-rose-100 p-3 text-rose-700">{moderationError}</p>}<div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{moderationPhotos.map((photo) => <article key={photo.id} className="overflow-hidden rounded-2xl bg-white shadow"><img src={photo.imageUrl} alt={`Foto de ${photo.contributor.name}`} className="h-40 w-full object-contain bg-slate-100"/><div className="p-3"><label className="flex gap-2 text-sm font-bold"><input type="checkbox" checked={selectedIds.includes(photo.id)} onChange={() => setSelectedIds((ids) => ids.includes(photo.id) ? ids.filter((id) => id !== photo.id) : [...ids, photo.id])}/>{photo.contributor.name}</label>{photo.contributor.message && <p className="mt-1 text-xs">{photo.contributor.message}</p>}<div className="mt-3 flex gap-2"><button disabled={moderating} onClick={() => void moderate([photo.id], 'approved')} className="rounded-lg bg-emerald-600 p-2 text-white" aria-label="Aprobar"><Check size={16}/></button><button disabled={moderating} onClick={() => void moderate([photo.id], 'hidden')} className="rounded-lg bg-slate-700 p-2 text-white" aria-label="Ocultar"><EyeOff size={16}/></button></div></div></article>)}</div></div></section>;
  const coverImage = String(value(settingsValues, key(moduleId, 'el_special_event_cover', 'image'), '')).trim();
  return <section className="@container" style={{ background: 'transparent', color: text }}><div className="mx-auto max-w-5xl px-4 py-8 sm:py-12"><header className="relative overflow-hidden rounded-3xl text-center" style={{ background: 'transparent' }}><div className="flex min-h-[360px] items-center justify-center" style={{ background: 'transparent' }}>{coverImage && <img src={coverImage} alt="Portada del evento" className="h-auto max-h-[72svh] w-full object-contain object-center md:h-[clamp(26rem,62vh,44rem)] md:max-w-full md:w-auto"/>}</div><div className="pointer-events-none absolute inset-0 flex flex-col justify-end p-8">{value(settingsValues, key(moduleId, 'el_special_event_cover', 'show_title'), true) && <h1 className="text-4xl font-black text-white drop-shadow">{title}</h1>}{value(settingsValues, key(moduleId, 'el_special_event_cover', 'show_subtitle'), true) && subtitle && <p className="text-white drop-shadow">{subtitle}</p>}</div></header>
  {story.length > 0 && <div className="mt-10"><div className="relative rounded-3xl bg-white p-3 shadow"><img src={story[slide]?.url} alt={story[slide]?.alt || 'Historia del evento'} className="h-80 w-full object-contain"/><button onClick={() => setSlide((slide - 1 + story.length) % story.length)} className="absolute left-5 top-1/2 rounded-full bg-white p-2"><ChevronLeft/></button><button onClick={() => setSlide((slide + 1) % story.length)} className="absolute right-5 top-1/2 rounded-full bg-white p-2"><ChevronRight/></button></div></div>}
  <div className="mt-10">{renderPublicEventDetails && <div className="rounded-3xl bg-white p-6 shadow"><h2 className="text-2xl font-black">Información del evento</h2><p>{value(settingsValues, key(moduleId, 'el_special_event_details', 'date'), '')} · {value(settingsValues, key(moduleId, 'el_special_event_details', 'time'), '')}</p><p>{value(settingsValues, key(moduleId, 'el_special_event_details', 'place'), '')}</p><p>{value(settingsValues, key(moduleId, 'el_special_event_details', 'address'), '')}</p>{/^https?:\/\//.test(value(settingsValues, key(moduleId, 'el_special_event_details', 'waze_url'), '')) && <a className="mt-4 inline-flex gap-2 rounded-xl px-4 py-3 font-bold text-white" style={{ background: primary }} target="_blank" rel="noreferrer" href={value(settingsValues, key(moduleId, 'el_special_event_details', 'waze_url'), '')}><MapPin size={18}/>Abrir en Waze</a>}</div>}<form onSubmit={submit} className="mx-auto max-w-2xl rounded-3xl bg-white p-6 shadow"><h2 className="text-2xl font-black">{value(settingsValues, key(moduleId, 'el_special_event_upload', 'heading'), 'Comparte tus recuerdos')}</h2><input className="mt-3 w-full rounded-xl border p-3" placeholder="Tu nombre" value={name} onChange={(e) => setName(e.target.value)} maxLength={120}/><textarea className="mt-3 w-full rounded-xl border p-3" placeholder="Mensaje opcional" value={message} onChange={(e) => setMessage(e.target.value)} maxLength={2000}/><input ref={fileRef} className="hidden" type="file" accept="image/jpeg,image/png" multiple onChange={(e) => pickFiles(e.target.files)}/><button type="button" onClick={() => fileRef.current?.click()} className="mt-3 flex w-full justify-center gap-2 rounded-xl border-2 border-dashed p-4"><Upload size={18}/>Seleccionar fotos ({files.length}/10)</button><div className="mt-2 flex flex-wrap gap-2">{files.map((file, index) => <button type="button" key={`${file.name}-${index}`} onClick={() => setFiles((current) => current.filter((_, item) => item !== index))} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{file.name} <X size={12} className="inline"/></button>)}</div>{uploading && <div className="mt-3 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full" style={{ width: `${progress}%`, background: primary }}/></div>}<button disabled={uploading || !slug} className="mt-4 w-full rounded-xl p-4 font-black text-white disabled:opacity-50" style={{ background: primary }}>{uploading ? `Subiendo ${progress}%` : 'Enviar fotografías'}</button>{notice && <p className="mt-3 text-sm">{notice}</p>}</form></div>
  <div className="mt-10"><div className="mb-4 flex gap-2 overflow-x-auto"><button onClick={() => setFilter('all')} className="rounded-full bg-white px-4 py-2">Todos</button>{contributors.map((contributor) => <button key={contributor.id} onClick={() => setFilter(contributor.id)} className="rounded-full bg-white px-4 py-2">{contributor.name}</button>)}</div><div className="columns-2 gap-3 sm:columns-3">{filtered.map((photo, index) => <button key={photo.id} onClick={() => setSelected(index)} className="mb-3 block w-full break-inside-avoid rounded-2xl bg-white p-2 text-left shadow"><img src={photo.imageUrl} alt={`Foto de ${photo.contributor.name}`} className="w-full object-contain"/><span className="p-2 text-sm font-bold">{photo.contributor.name}</span></button>)}</div></div>{selected !== null && filtered[selected] && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4" onClick={() => setSelected(null)}><img src={filtered[selected].imageUrl} alt="Foto ampliada" className="max-h-full max-w-full object-contain"/></div>}</div></section>;
};
