import assert from 'node:assert/strict';
import test from 'node:test';
import { checkPublicReservasWebContact, createPublicReservasWebReservation } from '../src/services/reservasWebPublicApi';

const input = { holdToken: 'active-public-hold-token-abcdefghijklmnopqrstuvwxyz', idempotencyKey: 'reservation-attempt-key', contactFirstName: 'Ana', contactLastName: 'Pérez', contactWhatsapp: '+506 8888 8888', paymentMethod: 'card' as const, participants: [{ firstName: 'Ana', lastName: 'Pérez', sex: 'female' as const, birthDate: '1990-01-01', identificationNumber: 'ID-1' }] };
test('public contact check and reservation submit use only their real public contracts', async () => {
  const originalFetch = globalThis.fetch; const requests: Array<{ url: string; init?: RequestInit }> = [];
  globalThis.fetch = (async (url: string, init?: RequestInit) => { requests.push({ url, init }); return requests.length === 1 ? new Response(JSON.stringify({ success: true, hasExistingReservation: true })) : new Response(JSON.stringify({ success: true, reservation: { reservationReference: 'RW-123', status: 'pending_payment', confirmedAt: null, reservedAt: '2099-01-01T00:00:00Z', paymentDueAt: '2099-01-02T00:00:00Z', quantity: 1, totalAmount: 20, requiredNow: 10, pendingBalance: 10, perPersonPaymentAmount: 10, paymentMode: 'deposit', depositRefundable: false, currency: 'USD', paymentUrl: 'https://pay.example.test/a', paymentReceiptWhatsapp: '+50688888888', payment: { method: 'card' } }, idempotentReplay: false }), { status: 201 }); }) as typeof fetch;
  try { assert.equal(await checkPublicReservasWebContact('public / id', input.contactWhatsapp, undefined, 'https://app.example.test'), true); const result = await createPublicReservasWebReservation(input, undefined, 'https://app.example.test'); assert.equal(result.reservation.status, 'pending_payment'); assert.equal(result.reservation.requiredNow, 10); assert.equal(result.reservation.perPersonPaymentAmount, 10); assert.equal(result.reservation.paymentUrl, 'https://pay.example.test/a'); assert.equal(requests[0].url, 'https://app.example.test/api/public/reservas-web/activities/public%20%2F%20id/check-contact'); assert.equal(requests[1].url, 'https://app.example.test/api/public/reservas-web/reservations'); assert.deepEqual(JSON.parse(String(requests[1].init?.body)), input); for (const request of requests) { assert.equal(request.init?.credentials, 'omit'); assert.equal('Authorization' in (request.init?.headers || {}), false); } } finally { globalThis.fetch = originalFetch; }
});
